### ISSUE TITLE
Issue in reproducing the results 

### ISSUE THREAD

**Issue by zaverichintan** [BII-wushuang/Lie-Group-Motion-Prediction#3]
Hello, 
I tried to run the linearized loss by making changes to the loss function as on: 
[Issue ](https://github.com/BII-wushuang/Lie-Group-Motion-Prediction/issues/2)

The numbers I am getting on evaluation are very weird and high for the Mean Joint Error. 
I have attached the files for the reference. Could you provide the checkpoints for model weights to reproduce the result?
[Errors_walking.xlsx](https://github.com/BII-wushuang/Lie-Group-Motion-Prediction/files/3529719/Errors_walking.xlsx)

**Comment by BII-wushuang** [comment]
Uploaded a [model checkpoint](https://github.com/BII-wushuang/Lie-Group-Motion-Prediction/blob/c360906dd2421814a6a63e115673a6d6842d457a/src/H3.6m_checkpoint.rar) in the latest commit.

**Comment by BII-wushuang** [comment]
The slight fluctuations in the results can be fixed upon fixing the random seeds. _c.f._ https://github.com/BII-wushuang/Lie-Group-Motion-Prediction/issues/4#issuecomment-882065337
The following set of random seeds, for example, would match the reported numbers.
```
random.seed(0)
np.random.seed(123456789)
tf.set_random_seed(123456789)
```

**Comment by Zaverichintanoxolo** [comment]
The reply is after 2 years of the initial question. I am no longer working on this. Kindly make sure to help promptly. Anyway, I found the method producing still motion predictions.

**Comment by zaverichintan** [comment]
The reply is after 2 years of the initial question. I am no longer working on this. Kindly make sure to help promptly. Anyway, I found the method producing still motion predictions. The updated code does not reproduce exact results.
