### ISSUE TITLE
Hard to download the code and data

### ISSUE THREAD

**Issue by hujb48** [BII-wushuang/Lie-Group-Motion-Prediction#7]
Hi, This is a great work, I would like to reproduct this project,
however, it is hard to download not only by command"git" but also download directly, 
the documents are always incomplete after "downloading",
and I try to use the proxy and it doesn't work,
so could you please upload the project to the google cload or any other place for the download operation!
Thanks again!
Yours, Hu

**Comment by BII-wushuang** [comment]
Hi Hu,

Thank you for your interest. I have uploaded the project code and data onto [Google Drive](https://drive.google.com/file/d/1jvnVwffoahznORLyjT6z48bSvp8Mhdd9/view?usp=sharing).

**Comment by hujb48** [comment]
Thanks a lot for your prompt reply! And I have succeed to download the project from your link.

**Comment by ZhenguangLiu** [comment]
> Thanks a lot for your prompt reply! And I have succeed to download the project from your link.

Thank you for your interest. Should you have any other problem, please feel free to contact us.
